const data={
  "Habitaciones":[["el baño","banheiro"],["la cocina","cozinha"],["el comedor","sala de jantar"],["el dormitorio","quarto"],["el salón","sala de estar"]],
  "Partes de la casa":[["el balcón","varanda"],["la escalera","escada"],["la pared","parede"],["la puerta","porta"],["el suelo","chão"],["el techo","teto"],["la ventana","janela"]],
  "Muebles":[["el armario","armário"],["la cama","cama"],["la mesa","mesa"],["la silla","cadeira"],["el sofá","sofá"]],
  "Ropa":[["la camiseta","camiseta"],["la chaqueta","jaqueta"],["el pantalón","calça"],["el pijama","pijama"],["las zapatillas","tênis"]],
  "Partes del cuerpo":[["el brazo","braço"],["la cabeza","cabeça"],["la mano","mão"],["la pierna","perna"],["el pie","pé"]]
};
const tabs=document.querySelector("#tabs"),grid=document.querySelector("#vocab-grid");
Object.keys(data).forEach((name,i)=>{const b=document.createElement("button");b.type="button";b.className=`tab${i===0?" active":""}`;b.textContent=name;b.dataset.category=name;tabs.appendChild(b)});
Object.entries(data).forEach(([cat,words])=>words.forEach(([es,pt])=>{const card=document.createElement("article");card.className="vocab-card";card.dataset.category=cat;card.innerHTML=`<strong>${es}</strong><button type="button" class="audio" data-speech="${es}">🔊</button><p>${pt}</p>`;grid.appendChild(card)}));
function filter(cat){document.querySelectorAll(".vocab-card").forEach(c=>c.classList.toggle("hide",c.dataset.category!==cat));document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t.dataset.category===cat))}filter("Habitaciones");
tabs.addEventListener("click",e=>{if(e.target.matches(".tab"))filter(e.target.dataset.category)});
function speak(text){if(!("speechSynthesis" in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="es-ES";const vs=speechSynthesis.getVoices();u.voice=vs.find(v=>v.lang.toLowerCase()==="es-es")||vs.find(v=>v.lang.startsWith("es"))||null;u.rate=.88;speechSynthesis.speak(u)}document.addEventListener("click",e=>{const b=e.target.closest("[data-speech]");if(b)speak(b.dataset.speech)});
const dialog=document.querySelector("#poster-dialog");document.querySelector("#open-poster").onclick=()=>dialog.showModal();document.querySelector("#close-poster").onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};
const norm=s=>s.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");document.querySelector("#check").onclick=()=>{const inputs=[...document.querySelectorAll("[data-answer]")];let n=0;inputs.forEach(i=>{const ok=norm(i.value)===norm(i.dataset.answer);i.classList.toggle("correct",ok);i.classList.toggle("wrong",!ok);if(ok)n++});document.querySelector("#score").textContent=`${n} de ${inputs.length} respuestas correctas.${n===inputs.length?" ¡Excelente!":" Revisa las respuestas marcadas."}`};
document.querySelector("#date").value=new Date().toLocaleDateString("en-CA");const form=document.querySelector("#lesson-form"),status=document.querySelector("#form-status"),submit=form.querySelector(".submit");form.onsubmit=async e=>{e.preventDefault();submit.disabled=true;submit.firstChild.textContent="Enviando... ";try{const r=await fetch(form.action,{method:"POST",body:new FormData(form)}),j=await r.json();if(!j.success)throw 0;status.textContent="¡Actividad enviada con éxito!";status.className="form-status success"}catch{status.textContent="No fue posible enviar la actividad. Comprueba tu conexión.";status.className="form-status error"}finally{submit.disabled=false;submit.firstChild.textContent="Enviar mi actividad "}};
